/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.sewsiaica.uusiaika.config;

/**
 *
 * @author iah1016
 */
public enum DefaultValues {
    DEFAULTPLAYERCHARISMA(10),
    DEFAULTPLAYERARGSKILLS(10),
    DEFAULTSECTBALANCE(5000),
    DEFAULTSECTEXPENSES(1000),
    DEFAULTSECTMEMBERFEE(100),
    DEFAULTVILPOPULATION(10),
    DEFAULTVILBASESCEPTICISM(10),
    DEFAULTVILBASESELFES(10),
    DEFAULTVILBASESELFAW(10),
    DEFAULTVILBASEARGSKILLS(10),
    DEFAULTVILBOUNDVALUE(51),
    DEFAULTCONVMAXNUMBEROFPERSUASIONS(3),
    DEFAULTCONVPERSPLAYERBOUND(20),
    DEFAULTCONVPERSVILBOUND(20),
    DEFAULTCONVPERSPLAYERCHARINCR(2),
    DEFAULTCONVPERSVILSELFAWDECR(5),
    DEFAULTCONVPERSVILSCEPTDECR(5),
    DEFAULTCONVMAXNUMBEROFSERMONS(2),
    DEFAULTCONVSERMPLAYERBOUND(20),
    DEFAULTCONVSERMVILBOUND(20),
    DEFAULTCONVSERMPLAYERCHARINCR(2),
    DEFAULTCONVSERMVILSCEPTDECR(5),
    DEFAULTCONVMAXNUMBEROFACCUSATIONS(2),
    DEFAULTCONVACCUPLAYERBOUND(20),
    DEFAULTCONVACCUVILBOUND(20),
    DEFAULTCONVACCUPLAYERCHARINCR(2),
    DEFAULTCONVACCUVILSELFESDECR(5),
    DEFAULTTURNINITIALNUMBEROFTURNS(0),
    DEFAULTTURNMAXNUMBEROFTURNS(100),
    DEFAULTTURNSCEPTINCRPERTURN(10),
    DEFAULTTURNTHRESHOLDFORSCEPTICISM(200),
    DEFAULTTEMPLESCEPTDECR(10),
    DEFAULTTEMPLEDEATHCULTCHARISMAREQ(255),
    DEFAULTTEMPLEDIVINERIGHTMONEYREQ(100000),
    DEFAULTTRAININGCHARISMAINCR(10),
    DEFAULTTRAININGARGSKILLSINCR(10);
    private final int value;

    private DefaultValues(int value) {
        this.value = value;
    }
    
    public int value() {
        return value;
    }
}
